[project]
name = "miniproject9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tofunmi Sodeinde", email = "tofsodeinde@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
miniproject9 = "miniproject9:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
